### ISSUE TITLE
[mobile] Страница blog, поправить шапку

### ISSUE THREAD

**Issue by alexbaumgertner** [up-htmlacademy/26591-pink#17]
Шапка меньше вьюпорта:
![screenshot at oct 26 23-21-40](https://cloud.githubusercontent.com/assets/223620/10741366/75738f96-7c38-11e5-9a13-9ea1b512767a.png)

**Comment by alexbaumgertner** [comment]
Скорее всего, причина:
```css
.wrapper {
    width: 280px; /* 320px? */
}
```
